/* Auto-generated by genmsg_cpp for file /tmp/buildd/ros-groovy-navigation-1.10.3/debian/ros-groovy-navigation/opt/ros/groovy/stacks/navigation/move_base_msgs/msg/MoveBaseResult.msg */
#ifndef MOVE_BASE_MSGS_MESSAGE_MOVEBASERESULT_H
#define MOVE_BASE_MSGS_MESSAGE_MOVEBASERESULT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace move_base_msgs
{
template <class ContainerAllocator>
struct MoveBaseResult_ {
  typedef MoveBaseResult_<ContainerAllocator> Type;

  MoveBaseResult_()
  {
  }

  MoveBaseResult_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::move_base_msgs::MoveBaseResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_base_msgs::MoveBaseResult_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct MoveBaseResult
typedef  ::move_base_msgs::MoveBaseResult_<std::allocator<void> > MoveBaseResult;

typedef boost::shared_ptr< ::move_base_msgs::MoveBaseResult> MoveBaseResultPtr;
typedef boost::shared_ptr< ::move_base_msgs::MoveBaseResult const> MoveBaseResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::move_base_msgs::MoveBaseResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::move_base_msgs::MoveBaseResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace move_base_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::move_base_msgs::MoveBaseResult_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::move_base_msgs::MoveBaseResult_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::move_base_msgs::MoveBaseResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::move_base_msgs::MoveBaseResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::move_base_msgs::MoveBaseResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "move_base_msgs/MoveBaseResult";
  }

  static const char* value(const  ::move_base_msgs::MoveBaseResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::move_base_msgs::MoveBaseResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
";
  }

  static const char* value(const  ::move_base_msgs::MoveBaseResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::move_base_msgs::MoveBaseResult_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::move_base_msgs::MoveBaseResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MoveBaseResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_base_msgs::MoveBaseResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::move_base_msgs::MoveBaseResult_<ContainerAllocator> & v) 
  {
  }
};


} // namespace message_operations
} // namespace ros

#endif // MOVE_BASE_MSGS_MESSAGE_MOVEBASERESULT_H

