#!/bin/sh

echo "Running setcap for youbot_driver..."
setcap cap_net_raw+ep /opt/ros/groovy/lib/youbot_driver/base_arm_gripper_test
setcap cap_net_raw+ep /opt/ros/groovy/lib/youbot_driver/displayIpAddress
echo "Linking libraries for youbot_driver..."
ln -s /opt/ros/groovy/share/youbot_driver/ld/groovy.conf /etc/ld.so.conf.d/groovy.conf 
ldconfig


echo "Setting up udev rule for hokuyo..."

echo '  copying the udev rule for the hokuyo to /etc/udev/rules.d/'
cp -f /opt/ros/groovy/share/youbot_driver/udev_rules/47-hokuyo.rules /etc/udev/rules.d/47-hokuyo.rules

echo '  This udev rule has two effects:'
echo '     a) it always grants correct permissions, and '
echo '     b) it creates a constant system link: /dev/sensors/hokuyo which can be used instead of /dev/ttyACM*. The latter one could change each time the Hokuyo is replugged.'

#via http://youbot-store.com/drivers/5/software.aspx
#and http://www.ros.org/wiki/hokuyo_node/Troubleshooting
